### ISSUE TITLE
How can I create a knowledge Article using sfdc.Knowledge object ?

### ISSUE THREAD

**Issue by abdulwahid24** [htarevern/salesforce-python-sdk#1]
Hi, 

I found your python package and its seems to be useful for integrating salesforce into python code. So I can create Contact as per your mentioned getting starting in README. But I don't how to create an knowledge article, I can see there is an object "sfdc.Knowledge". Can you guide me?

Thanks,
Abdul Wahid

**Comment by htarevern** [comment]
Hi Abdual,

I need to update the readme with better examples! I will make sure to do that soon. I am sorry about that.
Yes. You can insert into the sObject by sfdc.Knowledge.create() method.

I have couple examples in this slides too.
http://www.slideshare.net/hormoztarevern/salesforce-pythonsdk

Please let me know if you find bugs or have questions.

Thank you,

Hormoz Tarevern

**Comment by htarevern** [comment]
Hi Abdual,
I need to update the readme with better examples! I will make sure to do that soon. I am sorry about that.
Yes. You can insert into the sObject by sfdc.Knowledge.create() method.
I have couple examples in this slides too.
http://www.slideshare.net/hormoztarevern/salesforce-pythonsdk

Please let me know if you find bugs or have questions.
Thank you
Hormoz Tarevern 

```
 On Wednesday, December 31, 2014 12:25 AM, Abdul Wahid <notifications@github.com> wrote:
```

 Hi, I found your python package and its seems to be useful for integrating salesforce into python code. So I can create Contact as per your mentioned getting starting in README. But I don't how to create an knowledge article, I can see there is an object "sfdc.Knowledge". Can you guide me?Thanks,
Abdul Wahid—

**Comment by abdulwahid24** [comment]
Thanks for your response, I understood it clearly. Your design is really good and make developer work more easy.

So this how I created salesforce knowledge article,

Steps:
1. You must have an app on your salesforce account.
2. Get your client_id & client_sceret.
3. Also you need to get your access token from your personal settings on salesforce.com which will be append along with password such as

`sfdc.authenticate(client_id="CLIENT_ID", client_secret="CLIENT_SECRET", username="USERNAME/EMAIL", password="PASSWORD+ACCESS_TOKEN")`
1. Now you need to have enable knowledge user from your account settings.
2. Than create Article Type from Setup | Cutomize | Knowledge | Article Types ---> Create new.
3. Use your Article Type object name to create Article from API like this...

`sfdc.ARTICLE_OBJECT_NAME.create({'ARTICLE_FIELD_1': 'VALUE_1','ARTICLE_FIELD_2': 'VALUE_2', })`

This how I created Article from API.

Thanks @htarevern you really did awesome job.

Thanks again,
Abdul Wahid
